[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
event = "HK43FpG11qhqwHZT8ZuKqn8FPFpbYJj59QL1qvFpm1tx"

[programs.devnet]
event = "HK43FpG11qhqwHZT8ZuKqn8FPFpbYJj59QL1qvFpm1tx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/dezsomezo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
